### PR TITLE
fix(homepage-grid): Fixes issue with the homepage grid breaking on smaller browser window sizes.

### LINKED ISSUE #38: Bug: Check it out on tiles loses formatting on smaller screens
At an 1129 x 999 breakpoint, we lose formatting on a couple of the tiles.

image

### PR DESCRIPTION
**Pull request by markrickert**
Closes #38

I rearranged the grid contents a little:

1A90B946-6259-4DB3-B4B3-B48CF25C416C-28703-0000F825C533ED51

### CODE REVIEW

File: src/components/HomePageProjects/index.tsx [hunk 1]
```diff
@@ -1,42 +1,49 @@
-import Link from '@docusaurus/Link';
-import React from 'react';
-import clsx from 'clsx';
-import styles from './styles.module.css';
-import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
+import Link from "@docusaurus/Link";
```
Comment (trevor-coleman) [inline src/components/HomePageProjects/index.tsx:1]: not a blocker but looks like I need to adjust the linter config.

**Review by trevor-coleman — APPROVED** [review]
looks good!

File: src/components/HomePageProjects/index.tsx (hunk 1 above)
Comment (markrickert) [reply src/components/HomePageProjects/index.tsx:1]: Yeah, it wanted to change a bunch of stuff on save.
